version: '3.3'
services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      
      DOCKER_HOST: '192.168.10.120'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mydb_temp:/var/lib/mysql
      
    networks:
     db_network:
       ipv4_address: 197.0.0.2
      
      
      
      
  back:
    container_name: back
    image: backend_tarea3
    depends_on:
      - db
    ports:
      - '10000:10000'
    links: 
      - db
    networks:
     db_network:
       ipv4_address: 197.0.0.3
    environment:
      IP_ADDR: 197.0.0.2
      
    
  front:
    container_name: front
    image: front_tarea3
    depends_on:
      - back
    ports:
      - '80:80'
    links: 
      - back
    networks:
     db_network:
       ipv4_address: 197.0.0.4
    environment:
      REACT_APP_URL: 197.0.0.3
      
      
      
networks:
  db_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 197.0.0.0/24
      

# Names our volume
volumes:
  mydb_temp: 
  
